[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  USE_MOCK_DB = "flase"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
